### ISSUE TITLE
Stripe - Upgrade membership

### ISSUE THREAD

**Issue by liot-io** [ixartz/SaaS-Boilerplate#21]
Hi!

It seems there is no Stripe integration for signup to a paid account or upgrade to a pay account ? :)
How to integrate this into the Boilerplate please?

**Comment by ixartz** [comment]
Hi @liot-io,

In the future, it should have a Stripe integration. For the time being, if you need the Stripe integration, you can check out the official documentation.

Or, if you don't want to lose too much time implementing yourself or building from scratch, you can check out https://nextjs-boilerplate.com/pro-saas-starter-kit, the project include Stripe subscription payment out of the box. And, It's totally built on top of this project (SaaS-Boilerplate).

It's also a way to support the project, I'm planning to support this SaaS Boilerplate for several years.

**Comment by liot-io** [comment]
Hi @ixartz

How do i purchase it? And what is the price?

The 3 prices afe confusing to me? What are the difference?

søn. 2. jun. 2024 01.38 skrev Remi Wg ***@***.***>:

**Comment by ixartz** [comment]
Hi @liot-io 

Sorry for the confusion, it's new to me. No doubt I need to improve the wording and improve the landing page.

If you are interested, you can purchase directly with the previous link. You should be able to find the buy button and it'll redirect you to a Stripe checkout page for payment.

The difference between the price is based on the number of project you want to use and the number of developer who will work on the project. Otherwise, it's the same code and same feature.
